INSERT OR IGNORE INTO `units` (`id`, `base_unit_id`, `to_base_factor`, `to_base_offset`) VALUES
	('grams', 'grams', 1, 0),
	('kilograms', 'grams', 1000, 0),
	('milligrams', 'grams', 0.001, 0),
	('ounces', 'grams', 28.349523125, 0),
	('pounds', 'grams', 453.59237, 0),
	('milliliters', 'milliliters', 1, 0),
	('liters', 'milliliters', 1000, 0),
	('teaspoons', 'milliliters', 4.92892159375, 0),
	('tablespoons', 'milliliters', 14.78676478125, 0),
	('cups', 'milliliters', 236.5882365, 0),
	('fluid_ounces', 'milliliters', 29.5735295625, 0),
	('pints', 'milliliters', 473.176473, 0),
	('quarts', 'milliliters', 946.352946, 0),
	('gallons', 'milliliters', 3785.411784, 0),
	('each', 'each', 1, 0),
	('pinches', 'pinches', 1, 0),
	('dashes', 'dashes', 1, 0),
	('drops', 'drops', 1, 0),
	('pieces', 'pieces', 1, 0),
	('cloves', 'cloves', 1, 0),
	('slices', 'slices', 1, 0),
	('cans', 'cans', 1, 0),
	('bunches', 'bunches', 1, 0),
	('seconds', 'minutes', 0.0166666666666667, 0),
	('minutes', 'minutes', 1, 0),
	('hours', 'minutes', 60, 0),
	('celsius', 'celsius', 1, 0),
	('fahrenheit', 'celsius', 0.555555555555556, -17.7777777777778);

INSERT OR IGNORE INTO `unit_aliases` (`id`, `unit_id`, `base_unit_id`, `alias`, `locale`, `source_domain`, `default_for_locale`) VALUES
	('unit_alias_en_us_grams_default', 'grams', 'grams', 'g', 'en-US', NULL, 1),
	('unit_alias_en_us_grams_gram', 'grams', 'grams', 'gram', 'en-US', NULL, 0),
	('unit_alias_en_us_grams_grams', 'grams', 'grams', 'grams', 'en-US', NULL, 0),
	('unit_alias_en_us_kilograms_kg', 'kilograms', 'grams', 'kg', 'en-US', NULL, 0),
	('unit_alias_en_us_kilograms_kilogram', 'kilograms', 'grams', 'kilogram', 'en-US', NULL, 0),
	('unit_alias_en_us_kilograms_kilograms', 'kilograms', 'grams', 'kilograms', 'en-US', NULL, 0),
	('unit_alias_en_us_milligrams_mg', 'milligrams', 'grams', 'mg', 'en-US', NULL, 0),
	('unit_alias_en_us_milligrams_milligram', 'milligrams', 'grams', 'milligram', 'en-US', NULL, 0),
	('unit_alias_en_us_milligrams_milligrams', 'milligrams', 'grams', 'milligrams', 'en-US', NULL, 0),
	('unit_alias_en_us_ounces_oz', 'ounces', 'grams', 'oz', 'en-US', NULL, 0),
	('unit_alias_en_us_ounces_ounce', 'ounces', 'grams', 'ounce', 'en-US', NULL, 0),
	('unit_alias_en_us_ounces_ounces', 'ounces', 'grams', 'ounces', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_lb', 'pounds', 'grams', 'lb', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_lbs', 'pounds', 'grams', 'lbs', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_pound', 'pounds', 'grams', 'pound', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_pounds', 'pounds', 'grams', 'pounds', 'en-US', NULL, 0),
	('unit_alias_en_us_milliliters_default', 'milliliters', 'milliliters', 'ml', 'en-US', NULL, 1),
	('unit_alias_en_us_milliliters_milliliter', 'milliliters', 'milliliters', 'milliliter', 'en-US', NULL, 0),
	('unit_alias_en_us_milliliters_milliliters', 'milliliters', 'milliliters', 'milliliters', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_l', 'liters', 'milliliters', 'l', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_liter', 'liters', 'milliliters', 'liter', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_liters', 'liters', 'milliliters', 'liters', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_litre', 'liters', 'milliliters', 'litre', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_litres', 'liters', 'milliliters', 'litres', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_tsp', 'teaspoons', 'milliliters', 'tsp', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_tsp_period', 'teaspoons', 'milliliters', 'tsp.', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_teaspoon', 'teaspoons', 'milliliters', 'teaspoon', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_teaspoons', 'teaspoons', 'milliliters', 'teaspoons', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tbsp', 'tablespoons', 'milliliters', 'tbsp', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tbsp_period', 'tablespoons', 'milliliters', 'tbsp.', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tablespoon', 'tablespoons', 'milliliters', 'tablespoon', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tablespoons', 'tablespoons', 'milliliters', 'tablespoons', 'en-US', NULL, 0),
	('unit_alias_en_us_cups_cup', 'cups', 'milliliters', 'cup', 'en-US', NULL, 0),
	('unit_alias_en_us_cups_cups', 'cups', 'milliliters', 'cups', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fl_oz', 'fluid_ounces', 'milliliters', 'fl oz', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fl_oz_period', 'fluid_ounces', 'milliliters', 'fl. oz.', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fluid_ounce', 'fluid_ounces', 'milliliters', 'fluid ounce', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fluid_ounces', 'fluid_ounces', 'milliliters', 'fluid ounces', 'en-US', NULL, 0),
	('unit_alias_en_us_pints_pt', 'pints', 'milliliters', 'pt', 'en-US', NULL, 0),
	('unit_alias_en_us_pints_pint', 'pints', 'milliliters', 'pint', 'en-US', NULL, 0),
	('unit_alias_en_us_pints_pints', 'pints', 'milliliters', 'pints', 'en-US', NULL, 0),
	('unit_alias_en_us_quarts_qt', 'quarts', 'milliliters', 'qt', 'en-US', NULL, 0),
	('unit_alias_en_us_quarts_quart', 'quarts', 'milliliters', 'quart', 'en-US', NULL, 0),
	('unit_alias_en_us_quarts_quarts', 'quarts', 'milliliters', 'quarts', 'en-US', NULL, 0),
	('unit_alias_en_us_gallons_gal', 'gallons', 'milliliters', 'gal', 'en-US', NULL, 0),
	('unit_alias_en_us_gallons_gallon', 'gallons', 'milliliters', 'gallon', 'en-US', NULL, 0),
	('unit_alias_en_us_gallons_gallons', 'gallons', 'milliliters', 'gallons', 'en-US', NULL, 0),
	('unit_alias_en_us_each_default', 'each', 'each', 'each', 'en-US', NULL, 1),
	('unit_alias_en_us_each_ea', 'each', 'each', 'ea', 'en-US', NULL, 0),
	('unit_alias_en_us_each_count', 'each', 'each', 'count', 'en-US', NULL, 0),
	('unit_alias_en_us_pinches_pinch', 'pinches', 'pinches', 'pinch', 'en-US', NULL, 1),
	('unit_alias_en_us_pinches_pinches', 'pinches', 'pinches', 'pinches', 'en-US', NULL, 0),
	('unit_alias_en_us_dashes_dash', 'dashes', 'dashes', 'dash', 'en-US', NULL, 1),
	('unit_alias_en_us_dashes_dashes', 'dashes', 'dashes', 'dashes', 'en-US', NULL, 0),
	('unit_alias_en_us_drops_drop', 'drops', 'drops', 'drop', 'en-US', NULL, 1),
	('unit_alias_en_us_drops_drops', 'drops', 'drops', 'drops', 'en-US', NULL, 0),
	('unit_alias_en_us_pieces_piece', 'pieces', 'pieces', 'piece', 'en-US', NULL, 1),
	('unit_alias_en_us_pieces_pieces', 'pieces', 'pieces', 'pieces', 'en-US', NULL, 0),
	('unit_alias_en_us_cloves_clove', 'cloves', 'cloves', 'clove', 'en-US', NULL, 1),
	('unit_alias_en_us_cloves_cloves', 'cloves', 'cloves', 'cloves', 'en-US', NULL, 0),
	('unit_alias_en_us_slices_slice', 'slices', 'slices', 'slice', 'en-US', NULL, 1),
	('unit_alias_en_us_slices_slices', 'slices', 'slices', 'slices', 'en-US', NULL, 0),
	('unit_alias_en_us_cans_can', 'cans', 'cans', 'can', 'en-US', NULL, 1),
	('unit_alias_en_us_cans_cans', 'cans', 'cans', 'cans', 'en-US', NULL, 0),
	('unit_alias_en_us_bunches_bunch', 'bunches', 'bunches', 'bunch', 'en-US', NULL, 1),
	('unit_alias_en_us_bunches_bunches', 'bunches', 'bunches', 'bunches', 'en-US', NULL, 0),
	('unit_alias_en_us_minutes_default', 'minutes', 'minutes', 'min', 'en-US', NULL, 1),
	('unit_alias_en_us_minutes_minute', 'minutes', 'minutes', 'minute', 'en-US', NULL, 0),
	('unit_alias_en_us_minutes_minutes', 'minutes', 'minutes', 'minutes', 'en-US', NULL, 0),
	('unit_alias_en_us_seconds_s', 'seconds', 'minutes', 's', 'en-US', NULL, 0),
	('unit_alias_en_us_seconds_sec', 'seconds', 'minutes', 'sec', 'en-US', NULL, 0),
	('unit_alias_en_us_seconds_second', 'seconds', 'minutes', 'second', 'en-US', NULL, 0),
	('unit_alias_en_us_seconds_seconds', 'seconds', 'minutes', 'seconds', 'en-US', NULL, 0),
	('unit_alias_en_us_hours_h', 'hours', 'minutes', 'h', 'en-US', NULL, 0),
	('unit_alias_en_us_hours_hr', 'hours', 'minutes', 'hr', 'en-US', NULL, 0),
	('unit_alias_en_us_hours_hour', 'hours', 'minutes', 'hour', 'en-US', NULL, 0),
	('unit_alias_en_us_hours_hours', 'hours', 'minutes', 'hours', 'en-US', NULL, 0),
	('unit_alias_en_us_celsius_default', 'celsius', 'celsius', '°C', 'en-US', NULL, 1),
	('unit_alias_en_us_celsius_celsius', 'celsius', 'celsius', 'celsius', 'en-US', NULL, 0),
	('unit_alias_en_us_celsius_c', 'celsius', 'celsius', 'C', 'en-US', NULL, 0),
	('unit_alias_en_us_fahrenheit_f', 'fahrenheit', 'celsius', '°F', 'en-US', NULL, 0),
	('unit_alias_en_us_fahrenheit_fahrenheit', 'fahrenheit', 'celsius', 'fahrenheit', 'en-US', NULL, 0),
	('unit_alias_en_us_fahrenheit_letter', 'fahrenheit', 'celsius', 'F', 'en-US', NULL, 0),
	('unit_alias_nl_nl_teaspoons_tl', 'teaspoons', 'milliliters', 'tl', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_teaspoons_theelepel', 'teaspoons', 'milliliters', 'theelepel', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_teaspoons_theelepels', 'teaspoons', 'milliliters', 'theelepels', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_tablespoons_el', 'tablespoons', 'milliliters', 'el', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_tablespoons_eetlepel', 'tablespoons', 'milliliters', 'eetlepel', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_tablespoons_eetlepels', 'tablespoons', 'milliliters', 'eetlepels', 'nl-NL', NULL, 0);
-- Additional culinary units and localized aliases for recipe imports.
INSERT OR IGNORE INTO `units` (`id`, `base_unit_id`, `to_base_factor`, `to_base_offset`) VALUES
	('centiliters', 'milliliters', 10, 0),
	('deciliters', 'milliliters', 100, 0),
	('handfuls', 'handfuls', 1, 0),
	('sprigs', 'sprigs', 1, 0),
	('stalks', 'stalks', 1, 0),
	('leaves', 'leaves', 1, 0),
	('heads', 'heads', 1, 0),
	('bulbs', 'bulbs', 1, 0),
	('jars', 'jars', 1, 0),
	('bottles', 'bottles', 1, 0),
	('packages', 'packages', 1, 0),
	('packets', 'packets', 1, 0);

INSERT OR IGNORE INTO `unit_aliases` (`id`, `unit_id`, `base_unit_id`, `alias`, `locale`, `source_domain`, `default_for_locale`) VALUES
	('unit_alias_en_us_centiliters_cl', 'centiliters', 'milliliters', 'cl', 'en-US', NULL, 0),
	('unit_alias_en_us_centiliters_cL', 'centiliters', 'milliliters', 'cL', 'en-US', NULL, 0),
	('unit_alias_en_us_centiliters_centiliter', 'centiliters', 'milliliters', 'centiliter', 'en-US', NULL, 0),
	('unit_alias_en_us_centiliters_centiliters', 'centiliters', 'milliliters', 'centiliters', 'en-US', NULL, 0),
	('unit_alias_en_us_deciliters_dl', 'deciliters', 'milliliters', 'dl', 'en-US', NULL, 0),
	('unit_alias_en_us_deciliters_dL', 'deciliters', 'milliliters', 'dL', 'en-US', NULL, 0),
	('unit_alias_en_us_deciliters_deciliter', 'deciliters', 'milliliters', 'deciliter', 'en-US', NULL, 0),
	('unit_alias_en_us_deciliters_deciliters', 'deciliters', 'milliliters', 'deciliters', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_t', 'teaspoons', 'milliliters', 't', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_t_period', 'teaspoons', 'milliliters', 't.', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_T', 'tablespoons', 'milliliters', 'T', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_T_period', 'tablespoons', 'milliliters', 'T.', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tbl', 'tablespoons', 'milliliters', 'tbl', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tbls', 'tablespoons', 'milliliters', 'tbls', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tblsp', 'tablespoons', 'milliliters', 'tblsp', 'en-US', NULL, 0),
	('unit_alias_en_us_cups_c', 'cups', 'milliliters', 'c', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_hash', 'pounds', 'grams', '#', 'en-US', NULL, 0),
	('unit_alias_en_us_ounces_oz_period', 'ounces', 'grams', 'oz.', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_floz', 'fluid_ounces', 'milliliters', 'floz', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fl_oz_period_short', 'fluid_ounces', 'milliliters', 'fl oz.', 'en-US', NULL, 0),
	('unit_alias_en_us_handfuls_handful', 'handfuls', 'handfuls', 'handful', 'en-US', NULL, 1),
	('unit_alias_en_us_handfuls_handfuls', 'handfuls', 'handfuls', 'handfuls', 'en-US', NULL, 0),
	('unit_alias_en_us_sprigs_sprig', 'sprigs', 'sprigs', 'sprig', 'en-US', NULL, 1),
	('unit_alias_en_us_sprigs_sprigs', 'sprigs', 'sprigs', 'sprigs', 'en-US', NULL, 0),
	('unit_alias_en_us_stalks_stalk', 'stalks', 'stalks', 'stalk', 'en-US', NULL, 1),
	('unit_alias_en_us_stalks_stalks', 'stalks', 'stalks', 'stalks', 'en-US', NULL, 0),
	('unit_alias_en_us_leaves_leaf', 'leaves', 'leaves', 'leaf', 'en-US', NULL, 1),
	('unit_alias_en_us_leaves_leaves', 'leaves', 'leaves', 'leaves', 'en-US', NULL, 0),
	('unit_alias_en_us_heads_head', 'heads', 'heads', 'head', 'en-US', NULL, 1),
	('unit_alias_en_us_heads_heads', 'heads', 'heads', 'heads', 'en-US', NULL, 0),
	('unit_alias_en_us_bulbs_bulb', 'bulbs', 'bulbs', 'bulb', 'en-US', NULL, 1),
	('unit_alias_en_us_bulbs_bulbs', 'bulbs', 'bulbs', 'bulbs', 'en-US', NULL, 0),
	('unit_alias_en_us_jars_jar', 'jars', 'jars', 'jar', 'en-US', NULL, 1),
	('unit_alias_en_us_jars_jars', 'jars', 'jars', 'jars', 'en-US', NULL, 0),
	('unit_alias_en_us_bottles_bottle', 'bottles', 'bottles', 'bottle', 'en-US', NULL, 1),
	('unit_alias_en_us_bottles_bottles', 'bottles', 'bottles', 'bottles', 'en-US', NULL, 0),
	('unit_alias_en_us_packages_package', 'packages', 'packages', 'package', 'en-US', NULL, 1),
	('unit_alias_en_us_packages_packages', 'packages', 'packages', 'packages', 'en-US', NULL, 0),
	('unit_alias_en_us_packages_pkg', 'packages', 'packages', 'pkg', 'en-US', NULL, 0),
	('unit_alias_en_us_packets_packet', 'packets', 'packets', 'packet', 'en-US', NULL, 1),
	('unit_alias_en_us_packets_packets', 'packets', 'packets', 'packets', 'en-US', NULL, 0),
	('unit_alias_nl_nl_grams_g', 'grams', 'grams', 'g', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_grams_gram', 'grams', 'grams', 'gram', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_grams_gr', 'grams', 'grams', 'gr', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_kilograms_kg', 'kilograms', 'grams', 'kg', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_kilograms_kilo', 'kilograms', 'grams', 'kilo', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_kilograms_kilogram', 'kilograms', 'grams', 'kilogram', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_milliliters_ml', 'milliliters', 'milliliters', 'ml', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_milliliters_milliliter', 'milliliters', 'milliliters', 'milliliter', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_liters_l', 'liters', 'milliliters', 'l', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_liters_liter', 'liters', 'milliliters', 'liter', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_liters_ltr', 'liters', 'milliliters', 'ltr', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_centiliters_cl', 'centiliters', 'milliliters', 'cl', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_deciliters_dl', 'deciliters', 'milliliters', 'dl', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_deciliters_deciliter', 'deciliters', 'milliliters', 'deciliter', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_deciliters_deciliters', 'deciliters', 'milliliters', 'deciliters', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pinches_snuf', 'pinches', 'pinches', 'snuf', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pinches_snufje', 'pinches', 'pinches', 'snufje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pinches_snufjes', 'pinches', 'pinches', 'snufjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_dashes_scheut', 'dashes', 'dashes', 'scheut', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_dashes_scheutje', 'dashes', 'dashes', 'scheutje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pieces_stuk', 'pieces', 'pieces', 'stuk', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pieces_stuks', 'pieces', 'pieces', 'stuks', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_slices_plak', 'slices', 'slices', 'plak', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_slices_plakken', 'slices', 'slices', 'plakken', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cloves_teen', 'cloves', 'cloves', 'teen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cloves_teentje', 'cloves', 'cloves', 'teentje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cloves_tenen', 'cloves', 'cloves', 'tenen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cloves_teentjes', 'cloves', 'cloves', 'teentjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cans_blik', 'cans', 'cans', 'blik', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cans_blikken', 'cans', 'cans', 'blikken', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bunches_bos', 'bunches', 'bunches', 'bos', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bunches_bosje', 'bunches', 'bunches', 'bosje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_handfuls_handje', 'handfuls', 'handfuls', 'handje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_handfuls_handjes', 'handfuls', 'handfuls', 'handjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_sprigs_takje', 'sprigs', 'sprigs', 'takje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_sprigs_takjes', 'sprigs', 'sprigs', 'takjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_stalks_stengel', 'stalks', 'stalks', 'stengel', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_stalks_stengels', 'stalks', 'stalks', 'stengels', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_leaves_blaadje', 'leaves', 'leaves', 'blaadje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_leaves_blaadjes', 'leaves', 'leaves', 'blaadjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_heads_bol', 'heads', 'heads', 'bol', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_heads_bollen', 'heads', 'heads', 'bollen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bulbs_bol', 'bulbs', 'bulbs', 'bol', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bulbs_bollen', 'bulbs', 'bulbs', 'bollen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_jars_pot', 'jars', 'jars', 'pot', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_jars_potje', 'jars', 'jars', 'potje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_jars_potten', 'jars', 'jars', 'potten', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bottles_fles', 'bottles', 'bottles', 'fles', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bottles_flessen', 'bottles', 'bottles', 'flessen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packages_pak', 'packages', 'packages', 'pak', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packages_pakken', 'packages', 'packages', 'pakken', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packets_zak', 'packets', 'packets', 'zak', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packets_zakje', 'packets', 'packets', 'zakje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packets_zakjes', 'packets', 'packets', 'zakjes', 'nl-NL', NULL, 0);
