INSERT OR IGNORE INTO `units` (`id`, `base_unit_id`, `to_base_factor`, `to_base_offset`) VALUES
	('grams', 'grams', 1, 0),
	('kilograms', 'grams', 1000, 0),
	('milligrams', 'grams', 0.001, 0),
	('ounces', 'grams', 28.349523125, 0),
	('pounds', 'grams', 453.59237, 0),
	('milliliters', 'milliliters', 1, 0),
	('liters', 'milliliters', 1000, 0),
	('teaspoons', 'milliliters', 4.92892159375, 0),
	('tablespoons', 'milliliters', 14.78676478125, 0),
	('cups', 'milliliters', 236.5882365, 0),
	('fluid_ounces', 'milliliters', 29.5735295625, 0),
	('pints', 'milliliters', 473.176473, 0),
	('quarts', 'milliliters', 946.352946, 0),
	('gallons', 'milliliters', 3785.411784, 0),
	('each', 'each', 1, 0),
	('pinches', 'pinches', 1, 0),
	('dashes', 'dashes', 1, 0),
	('drops', 'drops', 1, 0),
	('pieces', 'pieces', 1, 0),
	('cloves', 'cloves', 1, 0),
	('slices', 'slices', 1, 0),
	('cans', 'cans', 1, 0),
	('bunches', 'bunches', 1, 0),
	('seconds', 'minutes', 0.0166666666666667, 0),
	('minutes', 'minutes', 1, 0),
	('hours', 'minutes', 60, 0),
	('celsius', 'celsius', 1, 0),
	('fahrenheit', 'celsius', 0.555555555555556, -17.7777777777778);

INSERT OR IGNORE INTO `unit_aliases` (`id`, `unit_id`, `base_unit_id`, `alias`, `locale`, `source_domain`, `default_for_locale`) VALUES
	('unit_alias_en_us_grams_default', 'grams', 'grams', 'g', 'en-US', NULL, 1),
	('unit_alias_en_us_grams_gram', 'grams', 'grams', 'gram', 'en-US', NULL, 0),
	('unit_alias_en_us_grams_grams', 'grams', 'grams', 'grams', 'en-US', NULL, 0),
	('unit_alias_en_us_kilograms_kg', 'kilograms', 'grams', 'kg', 'en-US', NULL, 0),
	('unit_alias_en_us_kilograms_kilogram', 'kilograms', 'grams', 'kilogram', 'en-US', NULL, 0),
	('unit_alias_en_us_kilograms_kilograms', 'kilograms', 'grams', 'kilograms', 'en-US', NULL, 0),
	('unit_alias_en_us_milligrams_mg', 'milligrams', 'grams', 'mg', 'en-US', NULL, 0),
	('unit_alias_en_us_milligrams_milligram', 'milligrams', 'grams', 'milligram', 'en-US', NULL, 0),
	('unit_alias_en_us_milligrams_milligrams', 'milligrams', 'grams', 'milligrams', 'en-US', NULL, 0),
	('unit_alias_en_us_ounces_oz', 'ounces', 'grams', 'oz', 'en-US', NULL, 0),
	('unit_alias_en_us_ounces_ounce', 'ounces', 'grams', 'ounce', 'en-US', NULL, 0),
	('unit_alias_en_us_ounces_ounces', 'ounces', 'grams', 'ounces', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_lb', 'pounds', 'grams', 'lb', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_lbs', 'pounds', 'grams', 'lbs', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_pound', 'pounds', 'grams', 'pound', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_pounds', 'pounds', 'grams', 'pounds', 'en-US', NULL, 0),
	('unit_alias_en_us_milliliters_default', 'milliliters', 'milliliters', 'ml', 'en-US', NULL, 1),
	('unit_alias_en_us_milliliters_milliliter', 'milliliters', 'milliliters', 'milliliter', 'en-US', NULL, 0),
	('unit_alias_en_us_milliliters_milliliters', 'milliliters', 'milliliters', 'milliliters', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_l', 'liters', 'milliliters', 'l', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_liter', 'liters', 'milliliters', 'liter', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_liters', 'liters', 'milliliters', 'liters', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_litre', 'liters', 'milliliters', 'litre', 'en-US', NULL, 0),
	('unit_alias_en_us_liters_litres', 'liters', 'milliliters', 'litres', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_tsp', 'teaspoons', 'milliliters', 'tsp', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_tsp_period', 'teaspoons', 'milliliters', 'tsp.', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_teaspoon', 'teaspoons', 'milliliters', 'teaspoon', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_teaspoons', 'teaspoons', 'milliliters', 'teaspoons', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tbsp', 'tablespoons', 'milliliters', 'tbsp', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tbsp_period', 'tablespoons', 'milliliters', 'tbsp.', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tablespoon', 'tablespoons', 'milliliters', 'tablespoon', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tablespoons', 'tablespoons', 'milliliters', 'tablespoons', 'en-US', NULL, 0),
	('unit_alias_en_us_cups_cup', 'cups', 'milliliters', 'cup', 'en-US', NULL, 0),
	('unit_alias_en_us_cups_cups', 'cups', 'milliliters', 'cups', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fl_oz', 'fluid_ounces', 'milliliters', 'fl oz', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fl_oz_period', 'fluid_ounces', 'milliliters', 'fl. oz.', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fluid_ounce', 'fluid_ounces', 'milliliters', 'fluid ounce', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fluid_ounces', 'fluid_ounces', 'milliliters', 'fluid ounces', 'en-US', NULL, 0),
	('unit_alias_en_us_pints_pt', 'pints', 'milliliters', 'pt', 'en-US', NULL, 0),
	('unit_alias_en_us_pints_pint', 'pints', 'milliliters', 'pint', 'en-US', NULL, 0),
	('unit_alias_en_us_pints_pints', 'pints', 'milliliters', 'pints', 'en-US', NULL, 0),
	('unit_alias_en_us_quarts_qt', 'quarts', 'milliliters', 'qt', 'en-US', NULL, 0),
	('unit_alias_en_us_quarts_quart', 'quarts', 'milliliters', 'quart', 'en-US', NULL, 0),
	('unit_alias_en_us_quarts_quarts', 'quarts', 'milliliters', 'quarts', 'en-US', NULL, 0),
	('unit_alias_en_us_gallons_gal', 'gallons', 'milliliters', 'gal', 'en-US', NULL, 0),
	('unit_alias_en_us_gallons_gallon', 'gallons', 'milliliters', 'gallon', 'en-US', NULL, 0),
	('unit_alias_en_us_gallons_gallons', 'gallons', 'milliliters', 'gallons', 'en-US', NULL, 0),
	('unit_alias_en_us_each_default', 'each', 'each', 'each', 'en-US', NULL, 1),
	('unit_alias_en_us_each_ea', 'each', 'each', 'ea', 'en-US', NULL, 0),
	('unit_alias_en_us_each_count', 'each', 'each', 'count', 'en-US', NULL, 0),
	('unit_alias_en_us_pinches_pinch', 'pinches', 'pinches', 'pinch', 'en-US', NULL, 1),
	('unit_alias_en_us_pinches_pinches', 'pinches', 'pinches', 'pinches', 'en-US', NULL, 0),
	('unit_alias_en_us_dashes_dash', 'dashes', 'dashes', 'dash', 'en-US', NULL, 1),
	('unit_alias_en_us_dashes_dashes', 'dashes', 'dashes', 'dashes', 'en-US', NULL, 0),
	('unit_alias_en_us_drops_drop', 'drops', 'drops', 'drop', 'en-US', NULL, 1),
	('unit_alias_en_us_drops_drops', 'drops', 'drops', 'drops', 'en-US', NULL, 0),
	('unit_alias_en_us_pieces_piece', 'pieces', 'pieces', 'piece', 'en-US', NULL, 1),
	('unit_alias_en_us_pieces_pieces', 'pieces', 'pieces', 'pieces', 'en-US', NULL, 0),
	('unit_alias_en_us_cloves_clove', 'cloves', 'cloves', 'clove', 'en-US', NULL, 1),
	('unit_alias_en_us_cloves_cloves', 'cloves', 'cloves', 'cloves', 'en-US', NULL, 0),
	('unit_alias_en_us_slices_slice', 'slices', 'slices', 'slice', 'en-US', NULL, 1),
	('unit_alias_en_us_slices_slices', 'slices', 'slices', 'slices', 'en-US', NULL, 0),
	('unit_alias_en_us_cans_can', 'cans', 'cans', 'can', 'en-US', NULL, 1),
	('unit_alias_en_us_cans_cans', 'cans', 'cans', 'cans', 'en-US', NULL, 0),
	('unit_alias_en_us_bunches_bunch', 'bunches', 'bunches', 'bunch', 'en-US', NULL, 1),
	('unit_alias_en_us_bunches_bunches', 'bunches', 'bunches', 'bunches', 'en-US', NULL, 0),
	('unit_alias_en_us_minutes_default', 'minutes', 'minutes', 'min', 'en-US', NULL, 1),
	('unit_alias_en_us_minutes_minute', 'minutes', 'minutes', 'minute', 'en-US', NULL, 0),
	('unit_alias_en_us_minutes_minutes', 'minutes', 'minutes', 'minutes', 'en-US', NULL, 0),
	('unit_alias_en_us_seconds_s', 'seconds', 'minutes', 's', 'en-US', NULL, 0),
	('unit_alias_en_us_seconds_sec', 'seconds', 'minutes', 'sec', 'en-US', NULL, 0),
	('unit_alias_en_us_seconds_second', 'seconds', 'minutes', 'second', 'en-US', NULL, 0),
	('unit_alias_en_us_seconds_seconds', 'seconds', 'minutes', 'seconds', 'en-US', NULL, 0),
	('unit_alias_en_us_hours_h', 'hours', 'minutes', 'h', 'en-US', NULL, 0),
	('unit_alias_en_us_hours_hr', 'hours', 'minutes', 'hr', 'en-US', NULL, 0),
	('unit_alias_en_us_hours_hour', 'hours', 'minutes', 'hour', 'en-US', NULL, 0),
	('unit_alias_en_us_hours_hours', 'hours', 'minutes', 'hours', 'en-US', NULL, 0),
	('unit_alias_en_us_celsius_default', 'celsius', 'celsius', '°C', 'en-US', NULL, 1),
	('unit_alias_en_us_celsius_celsius', 'celsius', 'celsius', 'celsius', 'en-US', NULL, 0),
	('unit_alias_en_us_celsius_c', 'celsius', 'celsius', 'C', 'en-US', NULL, 0),
	('unit_alias_en_us_fahrenheit_f', 'fahrenheit', 'celsius', '°F', 'en-US', NULL, 0),
	('unit_alias_en_us_fahrenheit_fahrenheit', 'fahrenheit', 'celsius', 'fahrenheit', 'en-US', NULL, 0),
	('unit_alias_en_us_fahrenheit_letter', 'fahrenheit', 'celsius', 'F', 'en-US', NULL, 0),
	('unit_alias_nl_nl_teaspoons_tl', 'teaspoons', 'milliliters', 'tl', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_teaspoons_theelepel', 'teaspoons', 'milliliters', 'theelepel', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_teaspoons_theelepels', 'teaspoons', 'milliliters', 'theelepels', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_tablespoons_el', 'tablespoons', 'milliliters', 'el', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_tablespoons_eetlepel', 'tablespoons', 'milliliters', 'eetlepel', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_tablespoons_eetlepels', 'tablespoons', 'milliliters', 'eetlepels', 'nl-NL', NULL, 0);
