-- Additional culinary units and localized aliases for recipe imports.
INSERT OR IGNORE INTO `units` (`id`, `base_unit_id`, `to_base_factor`, `to_base_offset`) VALUES
	('centiliters', 'milliliters', 10, 0),
	('deciliters', 'milliliters', 100, 0),
	('handfuls', 'handfuls', 1, 0),
	('sprigs', 'sprigs', 1, 0),
	('stalks', 'stalks', 1, 0),
	('leaves', 'leaves', 1, 0),
	('heads', 'heads', 1, 0),
	('bulbs', 'bulbs', 1, 0),
	('jars', 'jars', 1, 0),
	('bottles', 'bottles', 1, 0),
	('packages', 'packages', 1, 0),
	('packets', 'packets', 1, 0);

INSERT OR IGNORE INTO `unit_aliases` (`id`, `unit_id`, `base_unit_id`, `alias`, `locale`, `source_domain`, `default_for_locale`) VALUES
	('unit_alias_en_us_centiliters_cl', 'centiliters', 'milliliters', 'cl', 'en-US', NULL, 0),
	('unit_alias_en_us_centiliters_cL', 'centiliters', 'milliliters', 'cL', 'en-US', NULL, 0),
	('unit_alias_en_us_centiliters_centiliter', 'centiliters', 'milliliters', 'centiliter', 'en-US', NULL, 0),
	('unit_alias_en_us_centiliters_centiliters', 'centiliters', 'milliliters', 'centiliters', 'en-US', NULL, 0),
	('unit_alias_en_us_deciliters_dl', 'deciliters', 'milliliters', 'dl', 'en-US', NULL, 0),
	('unit_alias_en_us_deciliters_dL', 'deciliters', 'milliliters', 'dL', 'en-US', NULL, 0),
	('unit_alias_en_us_deciliters_deciliter', 'deciliters', 'milliliters', 'deciliter', 'en-US', NULL, 0),
	('unit_alias_en_us_deciliters_deciliters', 'deciliters', 'milliliters', 'deciliters', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_t', 'teaspoons', 'milliliters', 't', 'en-US', NULL, 0),
	('unit_alias_en_us_teaspoons_t_period', 'teaspoons', 'milliliters', 't.', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_T', 'tablespoons', 'milliliters', 'T', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_T_period', 'tablespoons', 'milliliters', 'T.', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tbl', 'tablespoons', 'milliliters', 'tbl', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tbls', 'tablespoons', 'milliliters', 'tbls', 'en-US', NULL, 0),
	('unit_alias_en_us_tablespoons_tblsp', 'tablespoons', 'milliliters', 'tblsp', 'en-US', NULL, 0),
	('unit_alias_en_us_cups_c', 'cups', 'milliliters', 'c', 'en-US', NULL, 0),
	('unit_alias_en_us_pounds_hash', 'pounds', 'grams', '#', 'en-US', NULL, 0),
	('unit_alias_en_us_ounces_oz_period', 'ounces', 'grams', 'oz.', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_floz', 'fluid_ounces', 'milliliters', 'floz', 'en-US', NULL, 0),
	('unit_alias_en_us_fluid_ounces_fl_oz_period_short', 'fluid_ounces', 'milliliters', 'fl oz.', 'en-US', NULL, 0),
	('unit_alias_en_us_handfuls_handful', 'handfuls', 'handfuls', 'handful', 'en-US', NULL, 1),
	('unit_alias_en_us_handfuls_handfuls', 'handfuls', 'handfuls', 'handfuls', 'en-US', NULL, 0),
	('unit_alias_en_us_sprigs_sprig', 'sprigs', 'sprigs', 'sprig', 'en-US', NULL, 1),
	('unit_alias_en_us_sprigs_sprigs', 'sprigs', 'sprigs', 'sprigs', 'en-US', NULL, 0),
	('unit_alias_en_us_stalks_stalk', 'stalks', 'stalks', 'stalk', 'en-US', NULL, 1),
	('unit_alias_en_us_stalks_stalks', 'stalks', 'stalks', 'stalks', 'en-US', NULL, 0),
	('unit_alias_en_us_leaves_leaf', 'leaves', 'leaves', 'leaf', 'en-US', NULL, 1),
	('unit_alias_en_us_leaves_leaves', 'leaves', 'leaves', 'leaves', 'en-US', NULL, 0),
	('unit_alias_en_us_heads_head', 'heads', 'heads', 'head', 'en-US', NULL, 1),
	('unit_alias_en_us_heads_heads', 'heads', 'heads', 'heads', 'en-US', NULL, 0),
	('unit_alias_en_us_bulbs_bulb', 'bulbs', 'bulbs', 'bulb', 'en-US', NULL, 1),
	('unit_alias_en_us_bulbs_bulbs', 'bulbs', 'bulbs', 'bulbs', 'en-US', NULL, 0),
	('unit_alias_en_us_jars_jar', 'jars', 'jars', 'jar', 'en-US', NULL, 1),
	('unit_alias_en_us_jars_jars', 'jars', 'jars', 'jars', 'en-US', NULL, 0),
	('unit_alias_en_us_bottles_bottle', 'bottles', 'bottles', 'bottle', 'en-US', NULL, 1),
	('unit_alias_en_us_bottles_bottles', 'bottles', 'bottles', 'bottles', 'en-US', NULL, 0),
	('unit_alias_en_us_packages_package', 'packages', 'packages', 'package', 'en-US', NULL, 1),
	('unit_alias_en_us_packages_packages', 'packages', 'packages', 'packages', 'en-US', NULL, 0),
	('unit_alias_en_us_packages_pkg', 'packages', 'packages', 'pkg', 'en-US', NULL, 0),
	('unit_alias_en_us_packets_packet', 'packets', 'packets', 'packet', 'en-US', NULL, 1),
	('unit_alias_en_us_packets_packets', 'packets', 'packets', 'packets', 'en-US', NULL, 0),
	('unit_alias_nl_nl_grams_g', 'grams', 'grams', 'g', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_grams_gram', 'grams', 'grams', 'gram', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_grams_gr', 'grams', 'grams', 'gr', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_kilograms_kg', 'kilograms', 'grams', 'kg', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_kilograms_kilo', 'kilograms', 'grams', 'kilo', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_kilograms_kilogram', 'kilograms', 'grams', 'kilogram', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_milliliters_ml', 'milliliters', 'milliliters', 'ml', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_milliliters_milliliter', 'milliliters', 'milliliters', 'milliliter', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_liters_l', 'liters', 'milliliters', 'l', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_liters_liter', 'liters', 'milliliters', 'liter', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_liters_ltr', 'liters', 'milliliters', 'ltr', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_centiliters_cl', 'centiliters', 'milliliters', 'cl', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_deciliters_dl', 'deciliters', 'milliliters', 'dl', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_deciliters_deciliter', 'deciliters', 'milliliters', 'deciliter', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_deciliters_deciliters', 'deciliters', 'milliliters', 'deciliters', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pinches_snuf', 'pinches', 'pinches', 'snuf', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pinches_snufje', 'pinches', 'pinches', 'snufje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pinches_snufjes', 'pinches', 'pinches', 'snufjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_dashes_scheut', 'dashes', 'dashes', 'scheut', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_dashes_scheutje', 'dashes', 'dashes', 'scheutje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pieces_stuk', 'pieces', 'pieces', 'stuk', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_pieces_stuks', 'pieces', 'pieces', 'stuks', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_slices_plak', 'slices', 'slices', 'plak', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_slices_plakken', 'slices', 'slices', 'plakken', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cloves_teen', 'cloves', 'cloves', 'teen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cloves_teentje', 'cloves', 'cloves', 'teentje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cloves_tenen', 'cloves', 'cloves', 'tenen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cloves_teentjes', 'cloves', 'cloves', 'teentjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cans_blik', 'cans', 'cans', 'blik', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_cans_blikken', 'cans', 'cans', 'blikken', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bunches_bos', 'bunches', 'bunches', 'bos', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bunches_bosje', 'bunches', 'bunches', 'bosje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_handfuls_handje', 'handfuls', 'handfuls', 'handje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_handfuls_handjes', 'handfuls', 'handfuls', 'handjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_sprigs_takje', 'sprigs', 'sprigs', 'takje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_sprigs_takjes', 'sprigs', 'sprigs', 'takjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_stalks_stengel', 'stalks', 'stalks', 'stengel', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_stalks_stengels', 'stalks', 'stalks', 'stengels', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_leaves_blaadje', 'leaves', 'leaves', 'blaadje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_leaves_blaadjes', 'leaves', 'leaves', 'blaadjes', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_heads_bol', 'heads', 'heads', 'bol', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_heads_bollen', 'heads', 'heads', 'bollen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bulbs_bol', 'bulbs', 'bulbs', 'bol', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bulbs_bollen', 'bulbs', 'bulbs', 'bollen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_jars_pot', 'jars', 'jars', 'pot', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_jars_potje', 'jars', 'jars', 'potje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_jars_potten', 'jars', 'jars', 'potten', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bottles_fles', 'bottles', 'bottles', 'fles', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_bottles_flessen', 'bottles', 'bottles', 'flessen', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packages_pak', 'packages', 'packages', 'pak', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packages_pakken', 'packages', 'packages', 'pakken', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packets_zak', 'packets', 'packets', 'zak', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packets_zakje', 'packets', 'packets', 'zakje', 'nl-NL', NULL, 0),
	('unit_alias_nl_nl_packets_zakjes', 'packets', 'packets', 'zakjes', 'nl-NL', NULL, 0);
