ALTER TABLE `unit_aliases` ADD COLUMN `plural_alias` text;
ALTER TABLE `unit_user_aliases` ADD COLUMN `plural_alias` text;
ALTER TABLE `unit_household_aliases` ADD COLUMN `plural_alias` text;

UPDATE `unit_aliases`
SET `plural_alias` = CASE `alias`
	WHEN 'teentje' THEN 'teentjes'
	WHEN 'teen' THEN 'tenen'
	WHEN 'clove' THEN 'cloves'
	WHEN 'eetlepel' THEN 'eetlepels'
	WHEN 'theelepel' THEN 'theelepels'
	WHEN 'tablespoon' THEN 'tablespoons'
	WHEN 'teaspoon' THEN 'teaspoons'
	WHEN 'cup' THEN 'cups'
	WHEN 'gram' THEN 'grams'
	WHEN 'kilogram' THEN 'kilograms'
	WHEN 'milliliter' THEN 'milliliters'
	WHEN 'liter' THEN 'liters'
	WHEN 'ounce' THEN 'ounces'
	WHEN 'pound' THEN 'pounds'
	WHEN 'piece' THEN 'pieces'
	WHEN 'slice' THEN 'slices'
	WHEN 'can' THEN 'cans'
	WHEN 'bunch' THEN 'bunches'
	WHEN 'handful' THEN 'handfuls'
	WHEN 'sprig' THEN 'sprigs'
	WHEN 'stalk' THEN 'stalks'
	WHEN 'leaf' THEN 'leaves'
	WHEN 'head' THEN 'heads'
	WHEN 'bulb' THEN 'bulbs'
	WHEN 'jar' THEN 'jars'
	WHEN 'bottle' THEN 'bottles'
	WHEN 'package' THEN 'packages'
	WHEN 'packet' THEN 'packets'
	WHEN 'pot' THEN 'potten'
	WHEN 'potje' THEN 'potjes'
	WHEN 'fles' THEN 'flessen'
	WHEN 'pak' THEN 'pakken'
	WHEN 'zak' THEN 'zakken'
	WHEN 'zakje' THEN 'zakjes'
	WHEN 'stuk' THEN 'stuks'
	WHEN 'plak' THEN 'plakken'
	WHEN 'bos' THEN 'bossen'
	WHEN 'bosje' THEN 'bosjes'
	WHEN 'snuf' THEN 'snuffen'
	WHEN 'snufje' THEN 'snufjes'
	WHEN 'scheut' THEN 'scheuten'
	WHEN 'scheutje' THEN 'scheutjes'
	WHEN 'takje' THEN 'takjes'
	WHEN 'stengel' THEN 'stengels'
	WHEN 'blaadje' THEN 'blaadjes'
	WHEN 'bol' THEN 'bollen'
	ELSE `plural_alias`
END
WHERE `plural_alias` IS NULL;
